# 4.1 NumPy를 사용한 벡터와 행렬의 연산

# Numpy 배열
리스트와 유사하지만, 수치해석용 array를 만드는 데 특화되어 있다.  
이는 같은 자료형만 들어가야 한다는 단점이 있으나 연산속도는 빠르게 만든다.

## NumPy 패키지 임포트 

In [2]:
import numpy as np

## 1차원 배열 만들기

In [5]:
ar = np.array([0, 1, 2, 3, 4, 5, 6,7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 벡터화 연산

In [7]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
answer = []
for di in data :
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [9]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [12]:
2*a + b

array([12, 24, 36])

In [14]:
a == 2

array([False,  True, False])

In [15]:
b > 10

array([False,  True,  True])

## 2차원 배열 만들기
ndarray는 N-dimensional Array의 약자이다.  
즉 1차원 배열(벡터)이외에도 다차원 배열 자료 구조를 지원한다.

In [17]:
c = np.array([[0, 1, 2], [3, 4, 5]]) #2 * 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
#행의 갯수
print(len(c))
#열의 갯수
print(len(c[0]))

2
3


### Exercise 4.1.1

In [23]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기
리스트의 리스트의 리스트를 이용하면 3차원 배열도 생성할 수 있다.
크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시.

In [25]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d #2층, 3*4 matrix

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [26]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [28]:
d.shape

(2, 3, 4)

In [31]:
#배열의 차원
d.ndim

3

## 배열의 인덱싱
일차원의 경우, 리스트의 인덱싱과 같다.  
다차원 배열의 경우에는 콤마를 사용해서 접근한다.

In [33]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
a[0,0]

0

## 배열 슬라이싱

In [35]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
a[0, :] #첫번째 행 전체

array([0, 1, 2, 3])

In [37]:
a[: ,1] #두번째 열 전체

array([1, 5])

In [38]:
a[1, 1:] #두번째 행의 두번째값부터 전체

array([5, 6, 7])

### Exercise 4.1.2
1. 이 행렬에서 값 7을 인덱싱한다.
2. 이 행렬에서 값 14를 인덱싱한다.
3. 이 행렬에서 배열 [6, 7]을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12]을 슬라이싱한다.
5. 이 행렬에서 배열[[3, 4], [8, 9]]을 슬라이싱한다.

In [39]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [41]:
#sol 1.
m[1, 2]

7

In [42]:
#sol 2.
m[2, -1]

14

In [46]:
#sol 3.
m[1, (1,2)]
m[1, 1:3]

array([6, 7])

In [47]:
#sol 4.
m[(1,2), 2]

array([ 7, 12])

In [49]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱
NumPy 배열 객체의 또다른 강력한 기능은 Fancy indexing이라고도 부르는 방법이다.  
이는 사실 데이터베이스의 질의(Query)기능을 수행한다.  
배열 인덱싱의 방식에는 Boolean 배열 방식과 정수 배열 방식 두가지가 있다.

In [51]:
#Boolean 배열방식
a = np.array(list(range(10)))
idx = np.array([True, False, True, False, True, False,
                True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [52]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [53]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [54]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [55]:
#정수 배열 방식
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [56]:
#이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없다.  
#같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 한다.

In [57]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원에서의 배열 인덱싱 활용

In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [61]:
a[[2, 0, 1], :]
#정수배열방식은 원하는 값을 지정하기 때문에, 순서 변경도 가능하다.

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### Exercise 4.1.3
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [63]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
#sol 1.
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [66]:
#sol 2.
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [67]:
#sol 3.
x[(x % 3 ==0) & (x % 4 ==1)]

array([9])

# 배열의 생성과 변형
## NumPy의 자료형
NumPy의 배열 즉, ndarray 클래스는 데이터가 같은 자료형이어야 한다.  
array명령으로 배열을 만들 때 자료형을 명시적으로 적용하려면 dtype 인수를 사용한다.
만약 dtype 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추한다.

In [68]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [69]:
x = np.array([.10, 2.0, 3.0])
x.dtype

dtype('float64')

In [70]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [71]:
#따로 지정할 수도 있다.
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [72]:
x[0] + x[1]

3.0

In [73]:
x = np.array([1, 2, 3], dtype='U')
x.dtype

dtype('<U1')

In [75]:
x[0] + x[1]

'12'

## Inf와 NaN
무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan을 사용할 수 있다.

In [76]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\jrchu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\jrchu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [77]:
print(np.log(0))
print(np.exp(-np.inf))

-inf
0.0


C:\Users\jrchu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


## 배열 생성
NumPy는 간단한 배열을 생성하는 다음과 같은 명령을 제공한다.  
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace
- rand, randn

In [80]:
#크기가 정해져 있고 모든 값이 0인 배열을 생성할때 사용하는 zeros 명령
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [82]:
#다차원 배열을 만들고자 할때는 인자로 튜플을 사용
b = np.zeros((2, 3), dtype='i')
b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [83]:
#문자열 배열도 생성할 수 있으나, 추후에 추가할 원소의 크기가 같아야 한다.
d = np.zeros(4, dtype='U4')
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'ABCDE'
d

array(['abc', 'abcd', 'ABCD', ''], dtype='<U4')

In [84]:
#0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다.
e = np.ones((2, 3, 4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [86]:
#만약 크기를 튜플로 명시하지 않고, 기존의 배열과 같은 크기로 만들고 싶으면
#ones_like, zeros_like 명령 사용
f = np.ones_like(b)
f

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [87]:
#배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸릴 수 있으므로
#배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 empty명령을 사용할 수 있다.

In [89]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
#arange명령은 numpy버전의 range명령이라고 볼 수 있다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(3, 21, 2) #끝값은 여전히 포함하지 않음

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

linspace, logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.

In [94]:
np.linspace(0, 100, 5) #시작, 끝(포함), 갯수

array([  0.,  25.,  50.,  75., 100.])

In [95]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치 연산
2차원 배열의 전치(Transpose) 연산은 행과 열을 바꾸는 작업이다.  
이는 배열의 T 속성으로 구할 수 있다.  
메서드가 아닌 속성이라는 점에 유의한다. (괄호가 붙지 않음)

In [96]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형 (reshape / flatten / ravel)

In [106]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
#사용하는 원소가 정해져 있기 때문에 reshape 명령의
#형태 튜플의 원소중 하나는 -1로 대체 가능하다.
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
a.reshape(2,2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [112]:
#다차원 배열을 무조건 1차원으로 펼치기 위해서는 flatten 또는 ravel 사용
(a.reshape(3, 4)).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행, 열의 갯수가 (5,1)인 2차원 배열 또는 행, 열의 갯수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.  
즉, 차원의 일치가 필요할 때에는 newaxis명령을 사용한다.

In [114]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [115]:
x.reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [116]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [117]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

## 배열 연결
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여(concatenate) 더 큰 배열을 만들 때는 다음과 같은 명령을 사용한다.
- hstack
- vstack
- dstack
- stack
- r_
- c_
- tile

In [118]:
#hstack
#행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다.
# cbind in r

In [122]:
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))

In [123]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [124]:
#vstack : rbind in r
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))

In [125]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
#dstack : 행이나 열이아닌 깊이(depth)의 방향으로 배열을 합친다.
#가장 끝에 값에 추가가 된다.
# 예제의 경우 2개의 (3*4) -> (3*4*2) 로 합쳐진다.

In [127]:
c1 = np.ones((3, 4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
c2 = np.zeros((3, 4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
print(np.dstack([c1, c2]))
print(np.dstack([c1, c2]).shape)

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


stack : dstack의 확장이다. 마지막 차원으로 연결하는 것이 아니라,  
직접 지정한 차원으로 배열을 연결한다. axis 인수 (디폴트 0)를 사용하여  
연결 후의 회전 방향을 정한다. -> 디폴드 값으로는 가장 앞쪽에 차원이 생성된다.

In [132]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [133]:
c.shape

(2, 3, 4)

In [134]:
c = np.stack([c1, c2], axis= 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [135]:
c.shape

(3, 2, 4)

r_ 메서드 : hstack과 비슷하게 배열을 좌우로 연결한다.

In [137]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
np.r_[A, B]
#이때, 대괄호를 사용한다. 이와 같은 특수 메서드를 인덱서라고 한다.

array([1, 2, 3, 4, 5, 6])

c_ 메서드 : 배열의 차원을 증가시킨 후 좌우로 연결한다.  
만약 1차원 배열을 연결하면, 2차원 배열이 된다.

In [138]:
np.c_[A, B]

array([[1, 4],
       [2, 5],
       [3, 6]])

tile 명령은 동일한 배열을 반복하여 연결한다.

In [139]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [140]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### Exercise 4.1.4

In [154]:
#sol1.
A = np.zeros((3, 3))
B = np.ones((3, 2))
C = (np.linspace(10, 150, 15)).reshape(3, -1)

V1 = np.hstack([A, B])
V2 = np.vstack([V1, C])
answer = np.tile(V2, (2,1))
answer


array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트(좌표쌍) 생성

In [155]:
x = np.arange(3)
x

array([0, 1, 2])

In [156]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [157]:
X, Y = np.meshgrid(x, y)

In [158]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [159]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [163]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [173]:
import matplotlib.pylab as plt

In [174]:
plt.title("np.meshgrid로 만든 Grid Points")
plt.scatter(X, Y, linewidths = 10)
plt.show()

# 배열의 연산
## 벡터화 연산

In [178]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [181]:
%%time
z = np.zeros_like(x)
for i in range(10000) :
    z[i] = x[i] + y[i]

Wall time: 3.99 ms


In [182]:
%%time
z = x + y

Wall time: 0 ns


사칙 연산 뿐만아니라 논리 연산도 벡터화 연산이 가능하다.

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

만약 배열의 각 원소들을 일일히 비교하는 것이 아니라 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령을 사용하면 된다.

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [6]:
np.all(a==b)

False

In [7]:
np.all(a==c)

True

In [8]:
a = np.arange(5)
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [9]:
10**a

array([    1,    10,   100,  1000, 10000], dtype=int32)